# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(538, 290)
        self.Message_label = QtWidgets.QLabel(Form)
        self.Message_label.setEnabled(True)
        self.Message_label.setGeometry(QtCore.QRect(60, 150, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.Message_label.setFont(font)
        self.Message_label.setObjectName("Message_label")
        self.Login_pushButton = QtWidgets.QPushButton(Form)
        self.Login_pushButton.setGeometry(QtCore.QRect(170, 200, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.Login_pushButton.setFont(font)
        self.Login_pushButton.setObjectName("Login_pushButton")
        self.password_lineEdit = QtWidgets.QLineEdit(Form)
        self.password_lineEdit.setGeometry(QtCore.QRect(120, 100, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.username_lineEdit = QtWidgets.QLineEdit(Form)
        self.username_lineEdit.setGeometry(QtCore.QRect(120, 40, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.username_lineEdit.setFont(font)
        self.username_lineEdit.setObjectName("username_lineEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Message_label.setText(_translate("Form", "Make sure you entered your Username and Password correctly."))
        self.Login_pushButton.setText(_translate("Form", "Login"))
        self.password_lineEdit.setPlaceholderText(_translate("Form", "Enter Password"))
        self.username_lineEdit.setPlaceholderText(_translate("Form", "Enter User Name"))
